### ISSUE TITLE
Unable to contact youtube

### ISSUE THREAD

**Issue by Nickwilde7755** [GaryOderNichts/GiveMiiYouTube#10]
Have confirmed internet connection

**Comment by nyathea** [comment]
Same :/

**Comment by Yeetov** [comment]
I had the same issue.

**Comment by GaryOderNichts** [comment]
It still works for me and others who have tested it. Make sure your Wii U has a stable Internet connection.

**Comment by nyathea** [comment]
> It still works for me and others who have tested it. Make sure your Wii U has a stable Internet connection.

The issue is that the version thats on NUSspli with a black icon doesn’t work but the youtube app with the red icon does. The red icon one for some reason isn’t on NUSspli

**Comment by Yeetov** [comment]
YouTube freezes even with the red version, it never loads

**Comment by coopeeo** [comment]
For people who downloaded the beta version of YouTube from NUSspli, go to the YouTube video linked on the bottom of this post, then go to the Google Drive link in the description of that video and extract the folder then put it on your sd card and install it via NUSspli.

https://www.youtube.com/watch?v=_sMrobQvBtI
