### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by SaulGoodman123** [GaryOderNichts/GiveMiiYouTube#3]
Tries to load, gives a "Cannot Connect to YouTube" error.

**Comment by GaryOderNichts** [comment]
Yeah, I can confirm this. Seems like YouTube changed something on their end.
I'll try to find what causes this exactly and if this can be worked around, if not this project is already dead again :P

**Comment by SaulGoodman123** [comment]
:P, still your enthusiasm is pretty nice and YouTube on the browser still works giving the TV interface.

**Comment by GaryOderNichts** [comment]
Fixed with version 2.0

**Comment by SaulGoodman123** [comment]
:D, could a patch like this be made for other services like Netflix?
