### ISSUE TITLE
Block Ads, Skip Sponsors, Skip Intro, Wii U Touch Gamepad and WiiRemote an Pro Controller in Wii U Youtube app

### ISSUE THREAD

**Issue by KrisGDC18** [GaryOderNichts/GiveMiiYouTube#7]
It would be great to be able to add these features to Wii U Youtube, apps like YT Vanced and ReVanced and extensions have the functionality to block those insatiable and harassing Google and YouTube ads, and skip annoying 5-10 minute sponsors who won't stop yelling at you how wonderful a junk product is, i don't know if this is possible, but in my opinion if it is, it would be great, adding other functions would be great too, like enabling touch on the gamepad or using the Wiiremote or Pro Controller to forget about the sometimes cumbersome Wii U Gamepad or forget about spending 4 years trying to find a video with buttons, without a doubt for Wii U owners it would be the favorite way to watch YouTube on TV to somehow add these functions.

**Comment by jonbarrow** [comment]
That is out of scope for this project. This application only serves to get the YouTube app to boot again, nothing more and nothing less. Additionally adding features such as blocking ads may get us under fire from Google as those features are given to paying users of YouTube. Vanced itself, which you mentioned, was already under fire of legal threats from Google for this very reason, and I do not plan to bring those issues to our project
