### ISSUE TITLE
Search for the original application

### ISSUE THREAD

**Issue by dluschan** [GaryOderNichts/GiveMiiYouTube#8]
Hello!
Please tell me where to get the youtube app after I deleted it.

**Comment by Umbreon-Dlc** [comment]
Oh just use Nusspli to download it, it should be there

**Comment by Umbreon-Dlc** [comment]
Alternatively you could use Wii U USB Helper

**Comment by GaryOderNichts** [comment]
Sorry, no support for obtaining the application if you didn't install it before the discontinuation.
